### ISSUE TITLE
Use graphic as pins not working

### ISSUE THREAD

**Issue by belal-almassri-spongeuk** [adaptlearning/adapt-contrib-hotgraphic#112]
I created a new course from the master branch and change the "_useGraphicsAsPins" to true, please find attached image to see result:

![hotgraphic](https://cloud.githubusercontent.com/assets/10432899/9902288/231fa11e-5c65-11e5-952d-fe337d793261.jpg)

**Comment by brian-learningpool** [comment]
Hi @belal-almassri-spongeuk, this setting requires some corresponding configuration on the classes in order to work as expected.  The documentation on this functionality is currently missing.

**Comment by belal-almassri-spongeuk** [comment]
@brian-learningpool Works fine once I added the classes, thanks a lot!!
