### ISSUE TITLE
Tabbing loses focus in item popup

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt-contrib-hotgraphic#120]
When tabbing through the default adapt build, the focus is lost when tabbing reaches the final text field in a hotgraphic's item popup. The focus returns to the top of the page, then to the instruction text on the narrative compoennt, and then finally on to the close button within the hotgraphic popup.

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#851
