### ISSUE TITLE
Request not issue

### ISSUE THREAD

**Issue by chrisgillison** [adaptlearning/adapt-contrib-hotgraphic#214]
Firstly, I love this component and love that it's regularly improved (making 'revert to narrative' on smaller screens optional is great)!

I remember the olden day when the popups didn't use notify. Using notify works just fine for most things, but the old way did allow you (with a little CSS) to use the 'popups' almost like tooltips, which could be just an image, or a tiny amount of text. If that's all you need from the popups, launching notify seems a bit like overkill!

What would be really great is if you had the option of either using notify (for more in depth content) , or a more tooltip-y handling of the popups like it used to be for lighter stuff. Just thought I'd put that out there (maybe it's just me!).

Great work, though.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt_framework/issues/3147
https://github.com/adaptlearning/adapt_framework/issues/2428

Something like this request?

**Comment by chrisgillison** [comment]
Ha! Completely exactly like that request! :)

**Comment by oliverfoster** [comment]
I'll close this one as duplicate. But you're definitely on record :+1:
