### ISSUE TITLE
Mobile Hot Graphics - switching orientation causes layout issue

### ISSUE THREAD

**Issue by tommy-bennett** [adaptlearning/adapt-contrib-hotgraphic#220]
### Mobile Hot Graphics - switching orientation causes layout issue

If the user views a Hot Graphic component in portrait mode (so it displays the Narrative mode w/ navigation arrows and plus sign), switches to landscape mode and then back to portrait mode, the Hot Graphic remains in its landscape mode display.

### Environment

* v5.19.0 Framework / v5.5.1 hotgraphic
* iPhone XR, iOS 15.3.1, Safari

### Steps to reproduce
* In mobile portrait orientation, navigate to a Hot Graphic component.
* Switch orientation to landscape.
* Switch orientation back to portrait mode.

### Expected behaviour
Upon switching to landscape mode, the Hot Graphic should change from a Narrative-style display with navigation arrows to a smaller version of the desktop Hot Graphic with pins. It should then revert to the Narrative-style display when switching back to portrait mode.

### Actual behaviour
Upon switching to landscape mode, the Hot Graphic changes from a Narrative-style display with navigation arrows to a smaller version of the desktop Hot Graphic with pins. However, upon switching back to portrait mode, the desktop-style Hot Graphic remains onscreen instead of it reverting back to the Narrative-style display.

### Screenshots
Initial portrait view:
![IMG_0064](https://user-images.githubusercontent.com/102748875/161093009-6c735697-ef5e-4995-b779-e4eb8fe66842.png)

Switching to landscape:
![IMG_0065](https://user-images.githubusercontent.com/102748875/161093071-f97c9ea9-c1bb-48e2-b2c1-56c7c05231be.png)

Switching back to portrait:
![IMG_0066](https://user-images.githubusercontent.com/102748875/161093118-8bc30f83-7c4e-4de3-8031-89a22fd2dc2c.png)

**Comment by oliverfoster** [comment]
Seems to be fixed. Sorry it's taken so long to verify @tommy-bennett
