### ISSUE TITLE
It opens very slowly、Have a sense of caton?

### ISSUE THREAD

**Issue by Rookie-zrx** [adaptlearning/adapt-contrib-hotgraphic#227]
![Recording 2022-05-10 at 15 48 50](https://user-images.githubusercontent.com/54833166/167576791-7586f4d3-0a26-4b7f-86b3-66586803e1f4.gif)
"version": "5.4.0",
It opens very slowly、Have a sense of caton?

**Comment by Rookie-zrx** [comment]
Caton feeling

**Comment by oliverfoster** [comment]
It doesn't work like this in a vanilla course. This is something to do with your theme.
![hotgraphic](https://user-images.githubusercontent.com/7974663/167587454-ce0a9e75-23d8-4ac1-b6ab-616ac6e87b37.gif)
