### ISSUE TITLE
adapt-contrib-hotgraphic: Pin Tooltip feature request

### ISSUE THREAD

**Issue by guywillis** [adaptlearning/adapt-contrib-hotgraphic#236]
The ability to add a tooltip to hotgraphic pins. Requested features:

- Tooltips can be set to show all the time OR only show on hover (auto enabled on all the time for touch devices).
- Tooltips can set to appear on each side of the pin AND / OR automatically attach the tooltip either left / right or top / bottom depending on whether there is enough available space to render.

Example of pin tooltip:
<img width="1006" alt="screen" src="https://user-images.githubusercontent.com/11569678/57144250-930ca400-6db8-11e9-8e7f-e4461732353d.png">

**Comment by oliverfoster** [comment]
duplicate of #239
