### ISSUE TITLE
Adjusting semantic differentiation between status and heading

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-hotgraphic#238]
### Subject of the issue/enhancement/features
A visited status is appended to the end of the aria-label string via innerHTML. Based on the changes recommend in the PR listed below, status indicators should come before the aria-label. I attempted to use insertAdjacentHTML to append the status to the label, but this resulted in the addition of unwanted quotation marks and line breaks within each component item aria-label. Is there a better way?

### Linked Issues
https://github.com/adaptlearning/adapt-contrib-core/issues/151
https://github.com/adaptlearning/adapt-contrib-core/pull/206

**Comment by oliverfoster** [comment]
Is this still needed @joe-replin ?

**Comment by joe-replin** [comment]
Yes, that is correct, @oliverfoster. I made a mistake by closing https://github.com/adaptlearning/adapt-contrib-core/pull/206 too early. In previous conversations we decided that status indicators in the aria-label should come first with a period separation so screen readers have a natural pause in the speech.

**Comment by oliverfoster** [comment]
I don't understand why your implementation is so complicated. Could you give a line example of where you've tried to move an existing visited status from the end to the start?

**Comment by joe-replin** [comment]
Sure. I'll use this as an example. Currently, we are using innerHTML to append the visited label to the end of the aria-label string. When I research for a prepend option to innerHTML, I'm presented with either prepend() or insertAdjacentHTML(). Using either function produces the following result in the output:
![image](https://user-images.githubusercontent.com/7740674/185416732-2f5c0f06-2ef0-4810-8a80-d858c52b8859.png)

I'm not sure why this is happening as all online docs suggest that neither function will produce line breaks & add quotes.

**Comment by joe-replin** [comment]
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/244
