### ISSUE TITLE
Use carousel behaviour from wcag

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-hotgraphic#243]
### Subject of the issue
Mark up items as list
https://www.w3.org/WAI/tutorials/carousels/

**Comment by joe-allen-89** [comment]
@oliverfoster currently the popup number is read out, as this has the number read out with the back/next button do we want to hide the popup number from screen readers? When testing it just seems to be a bit repetitive but happy either way.

**Comment by oliverfoster** [comment]
Can you do a pr for it so I can test and have a listen?

**Comment by joe-allen-89** [comment]
Of course, just thought I'd ask first, will sort the PR.

**Comment by oliverfoster** [comment]
It's always easier to understand with some code out front ;)
