### ISSUE TITLE
Should item pin number inherit from the icon styles?

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt-contrib-hotgraphic#282]
### Subject of the enhancement
With the current implementation (PR #281), the visited state pin displays larger than the unvisited number. The visited state inherits from `@icon-size` (`1.5rem`) whereas the number pin inherits from `@body-size` (`1rem`).

<img width="1491" alt="current_numbers" src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/7045330/a3b01529-b925-4a96-a6fd-f38734ad14b1">

Should `.hotgraphic__pin-number` inherit the icon styles instead for consistency of item size? See screenshot below.

<img width="1499" alt="numbers_inherit_from_icon" src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/7045330/2321efeb-df6b-4db4-9e91-d0b4491c1f81">

**Comment by swashbuck** [comment]
> we could update the .hotgraphic__pin-number to inherit the icon styles instead.

@kirsty-hames I prefer this option so that the pin circles don't change sizes once visited. I don't have a preference about inheriting from the icon styles or something else, as long as the pin circles don't change sizes.
