### ISSUE TITLE
Add text labels to pins

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-hotgraphic#303]
### Subject of the enhancement
We commonly customize Hot Graphics to show a text label by each pin. This would be a useful option when using either pin icons or pins as images (see below).

The position of each pin labels should be flexible. So, we would want options for `top` and `bottom` plus `left` and `right`.

Currently, we _can_ just add the text to the pin graphics themselves. However, this complicates localization since the graphics would need to be updated for additional languages.

### Screenshots

**Using pins**
<img src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/898168/45416dd2-6ebf-4c1f-9341-73065ac69741" width="450">

**Using pins as images**
<img src="https://github.com/adaptlearning/adapt-contrib-hotgraphic/assets/898168/f1cbf2d7-3ff2-4aea-b75d-591e6d11871e" width="450">

### Suggested configuration for an item
The new properties `label` and `_labelAlignment` would appear under `_pin`. `_labelAlignment` would default to `bottom`.
```
{
    "_left": 25,
    "_top": 25,
    "title": "Hotspot 1 title",
    "body": "This is display text 1.",
    "strapline": "Hotspot 1 strapline",
    "_imageAlignment": "right",
    "_classes": "",
    "_graphic": {
        "src": "course/en/images/example.jpg",
        "alt": "",
        "attribution": "Copyright © 2019",
        "_classes": ""
    },
    "_tooltip": {
        "_isEnabled": false,
        "text": "{{ariaLabel}}"
    },
    "_pin": {
        "src": "course/en/images/example.jpg",
        "alt": "",
        "label": "Pin label",
        "_labelAlignment": "top|bottom|left|right"
    }
},
```

**Comment by oliverfoster** [comment]
How does it scale onto mobile? Does the text size shrink also?

**Comment by swashbuck** [comment]
> How does it scale onto mobile? Does the text size shrink also?

@oliverfoster We could reduce the font size and label padding for mobile. This could also be managed on the design/AD end to ensure that hotspots are far enough apart and that there aren't too many hotspots (e.g. no more than 3 or so). Typically, we switch to Narrative or a static image for mobile views, though.

**Comment by oliverfoster** [comment]
Why for pin images only and not for normal pins?
Would you expect the tooltip and label to work together?

**Comment by swashbuck** [comment]
> Why for pin images only and not for normal pins? Would you expect the tooltip and label to work together?

@oliverfoster No, this would be for both pin types (see the apples & oranges screenshot above).

I think if we have a label, we would not have a need for a tooltip. To me, the purpose of the tooltip is to explain an icon or image when no text is present. I could be convinced otherwise, though.

**Comment by oliverfoster** [comment]
So it could be considered a permanent tooltip?

**Comment by swashbuck** [comment]
> So it could be considered a permanent tooltip?

Yes, I think that makes sense.
