### ISSUE TITLE
Migration: Use core mobileBody and mobileInstruction

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-hotgraphic#308]
### Subject of the enhancement
In this [core PR](https://github.com/adaptlearning/adapt-contrib-core/pull/539), the `mobileBody` and `mobileInstruction` properties will be added to the core header template. The [same](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/55b26b7fdae55f6c3d97384da2bd39e2d45e6616/schema/component.schema.json#L88) [properties](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/55b26b7fdae55f6c3d97384da2bd39e2d45e6616/schema/component.schema.json#L78) specific to this plugin should be removed. However, migration scripts will be needed so that we do not break existing builds.

### Dependencies
* https://github.com/adaptlearning/adapt-contrib-core/pull/539
* Migration scripts

**Comment by oliverfoster** [comment]
Please see: https://github.com/adaptlearning/adapt-contrib-narrative/issues/302#issuecomment-2146861450

**Comment by swashbuck** [comment]
Ok, yep, makes sense. Only the core template was updated rather than the schemas. Will close this ticket.
