### ISSUE TITLE
Add class when using numbered pins

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-hotgraphic#320]
### Subject of the enhancement
It would be useful to add a class (e.g. `has-numbered-pins`) to the Hot Graphic when numbered pins are used. This will help with theming. I tried using the `:has` selector like `:has(.hotgraphic__pin-number)` but the pin number element is removed after the item is visited.

```
"_useNumberedPins": true
```

Are there any other utility classes we should add to assist with theming? Do we need a class to indicate `_useGraphicsAsPins` is being used?

**Comment by kirsty-hames** [comment]
> Are there any other utility classes we should add to assist with theming? Do we need a class to indicate `_useGraphicsAsPins` is being used?

`_useGraphicsAsPins` is already covered by ['is-tile' or 'is-pin'](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/d273e8760670373f7ca2ba84a2704678305d24a2/templates/hotgraphic.jsx#L18) classes. I think all config options have a relevant class now that you've updated `_useNumberedPins`.
