### ISSUE TITLE
Add support for 'setCompletionOn' attribute

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-hotgraphic#55]
Similar to the media element, this should take 'inview' as a possible option to allow completion when the hotgraphic is used.  Raised because hotgraphic, e.g. for infographic type images, shrinking to a narrative on mobile can cause problems with completion.

**Comment by taylortom** [comment]
Moved to: https://adaptlearning.atlassian.net/browse/ABU-489
