### ISSUE TITLE
Various UI enhancements to hotgraphic

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-hotgraphic#77]
I'm proposing the following enhancements in order to facilitate a more flexible hotgraphic:
- Support for hiding pagination.  This has been requested by several end users, as currently once the first pin is activate it's possible to page completely through the remaining items.
- Changes to allow more specific styling of pins and the currently selected item.  This is just a matter of more specific classes on the markup.

**Comment by oliverfoster** [comment]
+1*10^MAX_INT

Just the normal notify works well for the hidden pagination. We did that recently in one of our courses... somewhere... 

Pin styling has also been requested by designers here, we haven't quite got into an implementation yet, mostly because of the difficulty creating the drop point of each icon. i.e. the tear drop is bottom center, a cross would be middle center etc. The simple the better in my opinion. What were you thinking?

**Comment by oliverfoster** [comment]
I see from #78 the hidden pagination. Cool.

**Comment by brian-learningpool** [comment]
Regarding the pin styling, we have designers requesting things like irregular sized tiled areas, not really pins in the traditional sense at all.  We have some concepts for things like zooming and scaling over item graphics.  

I think these enhancements will go a long way into reducing the current 'squareness' of this component and allow us all a bit more flexibility.

**Comment by moloko** [comment]
Great suggestions.

**Comment by zenduo** [comment]
Hey, looks like master got these lovely enhancements from @brian-learningpool, however these don't feature in the develop branch (not that I could see).

Here was the original pull that went into master:
https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/78

Would this be able to go into the develop branch or would it cause issues?

**Comment by moloko** [comment]
hmm not sure but I will add a ticket in Jira asking that someone look at this as it needs to be done for the v2 release

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-465
