### ISSUE TITLE
Hot graphic completion when changing orientation on mobile device

### ISSUE THREAD

**Issue by Ariiz91** [adaptlearning/adapt-contrib-hotgraphic#89]
Scenario: There is hot graphic component with 3 items to view.

When using hot graphic component in landscape orientation, and switching to portrait orientation to complete some of the items. Results in items that were viewed in portrait not being marked as complete when switching back to landscape orientation.

Steps to reproduce - use landscape orientation:
1. Click on the first item - close pop up - now item will be marked as complete 
2. Switch orientation (hot graphic component is changed to slider)
3. Now click on '+' for other two items
4. Go back to landscape orientation
5. The other two items you just viewed in portrait orientation are not marked as complete.

**Comment by guywillis** [comment]
This issue was moved to adaptlearning/adapt_framework#848
